// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchedulingMeruap.Api.Data;

#nullable disable

namespace SchedulingMeruap.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchedulingMeruap.Api.Models.ActivityLog", b =>
                {
                    b.Property<string>("LogId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("LOG_ID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("DOCUMENT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("LAST_NAME");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("POSITION");

                    b.Property<string>("ScheduleId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("SCHEDULE_ID");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TEAM");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("TYPE");

                    b.HasKey("LogId");

                    b.HasIndex(new[] { "ScheduleId" }, "SCHEDULE_INDX");

                    b.ToTable("ACTIVITY_LOG", (string)null);
                });

            modelBuilder.Entity("SchedulingMeruap.Api.Models.NewHire", b =>
                {
                    b.Property<string>("NewHireId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("NEW_HIRE_ID");

                    b.Property<string>("ActivationToken")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("ACTIVATION_TOKEN");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime")
                        .HasColumnName("JOIN_DATE");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("LAST_NAME");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("PHONE");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("POSITION");

                    b.Property<byte>("Sex")
                        .HasColumnType("tinyint")
                        .HasColumnName("SEX");

                    b.Property<DateTime>("TokenExpiry")
                        .HasColumnType("datetime")
                        .HasColumnName("TOKEN_EXPIRY");

                    b.HasKey("NewHireId");

                    b.HasIndex(new[] { "ActivationToken" }, "ACTIVATION_TOKEN_INDX")
                        .IsUnique();

                    b.HasIndex(new[] { "FirstName" }, "FIRST_NAME_INDX");

                    b.HasIndex(new[] { "LastName" }, "LAST_NAME_INDX");

                    b.HasIndex(new[] { "Position" }, "POSITON_INDX");

                    b.ToTable("NEW_HIRE", (string)null);
                });

            modelBuilder.Entity("SchedulingMeruap.Api.Models.Schedule", b =>
                {
                    b.Property<string>("ScheduleId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("SCHEDULE_ID");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("DATE");

                    b.HasKey("ScheduleId");

                    b.HasIndex(new[] { "Date" }, "DATE_INDX");

                    b.ToTable("SCHEDULE", (string)null);
                });

            modelBuilder.Entity("SchedulingMeruap.Api.Models.Shift", b =>
                {
                    b.Property<string>("ShiftId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("SHIFT_ID");

                    b.Property<string>("ScheduleId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("SCHEDULE_ID");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("TEAM_ID");

                    b.HasKey("ShiftId");

                    b.HasIndex(new[] { "ScheduleId" }, "SCHEDULE_INDX");

                    b.HasIndex(new[] { "TeamId" }, "TEAM_INDX");

                    b.ToTable("SHIFT", (string)null);
                });

            modelBuilder.Entity("SchedulingMeruap.Api.Models.Staff", b =>
                {
                    b.Property<string>("StaffId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("STAFF_ID");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime")
                        .HasColumnName("DOB");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime")
                        .HasColumnName("JOIN_DATE");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("LAST_NAME");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("PHONE");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("POSITION");

                    b.Property<byte>("Sex")
                        .HasColumnType("tinyint")
                        .HasColumnName("SEX");

                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("USER_ID");

                    b.HasKey("StaffId");

                    b.HasIndex(new[] { "FirstName" }, "FIRST_NAME_INDX");

                    b.HasIndex(new[] { "LastName" }, "LAST_NAME_INDX");

                    b.HasIndex(new[] { "Position" }, "POSITON_INDX");

                    b.HasIndex(new[] { "UserId" }, "USER_INDX");

                    b.ToTable("STAFF", (string)null);
                });

            modelBuilder.Entity("SchedulingMeruap.Api.Models.StaffTeam", b =>
                {
                    b.Property<string>("StaffTeamId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("STAFF_TEAM_ID");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("STAFF_ID");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("TEAM_ID");

                    b.HasKey("StaffTeamId");

                    b.HasIndex(new[] { "StaffId" }, "STAFF_INDX");

                    b.HasIndex(new[] { "TeamId" }, "TEAM_INDX");

                    b.ToTable("STAFF_TEAM", (string)null);
                });

            modelBuilder.Entity("SchedulingMeruap.Api.Models.Team", b =>
                {
                    b.Property<string>("TeamId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("TEAM_ID");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TEAM_NAME");

                    b.HasKey("TeamId");

                    b.HasIndex(new[] { "TeamName" }, "TEAM_NAME_INDX");

                    b.ToTable("TEAM", (string)null);
                });

            modelBuilder.Entity("SchedulingMeruap.Api.Models.Ticket", b =>
                {
                    b.Property<string>("TicketId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("TICKET_ID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("END_DATE");

                    b.Property<string>("Reason")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("REASON");

                    b.Property<string>("StaffId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("STAFF_ID");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("START_DATE");

                    b.Property<byte>("Status")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("tinyint")
                        .HasColumnName("STATUS");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TITLE");

                    b.Property<byte>("Type")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("tinyint")
                        .HasColumnName("TYPE");

                    b.HasKey("TicketId");

                    b.HasIndex(new[] { "StaffId" }, "STAFF_INDX");

                    b.HasIndex(new[] { "Title" }, "TITLE_INDX");

                    b.ToTable("TICKET", (string)null);
                });

            modelBuilder.Entity("SchedulingMeruap.Api.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("USER_ID");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("EMAIL");

                    b.Property<bool>("Locked")
                        .HasColumnType("bit")
                        .HasColumnName("LOCKED");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("PASSWORD");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "EMAIL_INDX");

                    b.ToTable("USER", (string)null);
                });

            modelBuilder.Entity("SchedulingMeruap.Api.Models.ActivityLog", b =>
                {
                    b.HasOne("SchedulingMeruap.Api.Models.Schedule", "Schedule")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("ScheduleId")
                        .IsRequired()
                        .HasConstraintName("FK_ACTIVITY_REFERENCE_SCHEDULE");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("SchedulingMeruap.Api.Models.Shift", b =>
                {
                    b.HasOne("SchedulingMeruap.Api.Models.Schedule", "Schedule")
                        .WithMany("Shifts")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SHIFT_REFERENCE_SCHEDULE");

                    b.HasOne("SchedulingMeruap.Api.Models.Team", "Team")
                        .WithMany("Shifts")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SHIFT_REFERENCE_TEAM");

                    b.Navigation("Schedule");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SchedulingMeruap.Api.Models.Staff", b =>
                {
                    b.HasOne("SchedulingMeruap.Api.Models.User", "User")
                        .WithMany("Staff")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_STAFF_REFERENCE_USER");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchedulingMeruap.Api.Models.StaffTeam", b =>
                {
                    b.HasOne("SchedulingMeruap.Api.Models.Staff", "Staff")
                        .WithMany("StaffTeams")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_STAFF_TE_REFERENCE_STAFF");

                    b.HasOne("SchedulingMeruap.Api.Models.Team", "Team")
                        .WithMany("StaffTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_STAFF_TE_REFERENCE_TEAM");

                    b.Navigation("Staff");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SchedulingMeruap.Api.Models.Ticket", b =>
                {
                    b.HasOne("SchedulingMeruap.Api.Models.Staff", "Staff")
                        .WithMany("Tickets")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_TICKET_REFERENCE_STAFF");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("SchedulingMeruap.Api.Models.Schedule", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("SchedulingMeruap.Api.Models.Staff", b =>
                {
                    b.Navigation("StaffTeams");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("SchedulingMeruap.Api.Models.Team", b =>
                {
                    b.Navigation("Shifts");

                    b.Navigation("StaffTeams");
                });

            modelBuilder.Entity("SchedulingMeruap.Api.Models.User", b =>
                {
                    b.Navigation("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
